### ISSUE TITLE
为什么在HRCAE.py和train_val_test.py中的norm函数选择的dim不一样？

### ISSUE THREAD

**Issue by zhulewen1998** [yanshen0210/HRCAE#1]
请问,在HRCAE.py中，denorm = x.norm(p=2,dim=2)*y.norm(p=2,dim=2);但是在utils/train_val_test.py中denorm = x.norm(p=2,dim=1)*y.norm(p=2,dim=1)。为什么同样是计算相似度，采用的dim却不一样？请问这个有什么解释吗？

**Comment by yanshen0210** [comment]
在HRCAE.py中，x和y的shape为torch.Size([128, 3, 512])，第一个维度为batch
size。dim=2为计算最后一个维度(512)的 L2 范数。
在utils/train_val_test.py中，x和y的shape为torch.Size([3,
512])，即输入是单个样本。dim=1也是计算最后一个维度(512)的 L2 范数。
希望能解决到你的疑惑，谢谢！


颜深


Zhu Lewen ***@***.***> 于2023年7月2日周日 14:25写道：
