### ISSUE TITLE
在datasers/data_load.py中 的def data_load(args,root):函数start,end=10000,10000+args.sample_length

### ISSUE THREAD

**Issue by zhulewen1998** [yanshen0210/HRCAE#2]
请问，在datasers/data_load.py中 的def data_load(args,root):函数，该行代码start,end=10000,10000+args.sample_length。
为什么不从0开始采样，要从10000开始采样？谢谢你

**Comment by yanshen0210** [comment]
因为数据量很充足，随机选的初始值，想着避免采样点开始可能出现的噪声数据。
这个值没啥实际意义，你可以自己根据需求改就行。

Zhu Lewen ***@***.***> 于2023年7月2日周日 22:23写道：

**Comment by zhulewen1998** [comment]
看到您的代码，里面有4个csv文件，都是c1的，都是c_1_002.csv,c_1_003.csv,c_1_004.csv,c_1_212.csv。但是您的论文里有c4和c6，但代码里并没有使用c4和c6，是不是c1就足够来做异常检测了？然后是，c1文件夹里有c1_1_1到c1_1_315，还有一个c1_wear.csv，不太理解为什么c_1_212.csv代表异常数据。这个是怎么选取的？为什么没有使用这个磨损数据c1_wear.csv？还有您的这个代码可以应用于轴承故障诊断吗？就是比如使用凯斯西储大学数据集，是一维数据，而您的代码是三通道，我自己怎么权衡，从哪些方面入手更改代码？谢谢您。因为自己不太能入手。

**Comment by zhulewen1998** [comment]
> 

看到您的代码，里面有4个csv文件，都是c1的，都是c_1_002.csv,c_1_003.csv,c_1_004.csv,c_1_212.csv。但是您的论文里有c4和c6，但代码里并没有使用c4和c6，是不是c1就足够来做异常检测了？然后是，c1文件夹里有c1_1_1到c1_1_315，还有一个c1_wear.csv，不太理解为什么c_1_212.csv代表异常数据。这个是怎么选取的？为什么没有使用这个磨损数据c1_wear.csv？还有您的这个代码可以应用于轴承故障诊断吗？就是比如使用凯斯西储大学数据集，是一维数据，而您的代码是三通道，我自己怎么权衡，从哪些方面入手更改代码？谢谢您。因为自己不太能入手。
