### ISSUE TITLE
请问您的这个代码该怎么应用于轴承故障诊断多分类？打扰您了

### ISSUE THREAD

**Issue by zhulewen1998** [yanshen0210/HRCAE#3]
看到您的代码，里面有4个csv文件，都是c1的，都是c_1_002.csv,c_1_003.csv,c_1_004.csv,c_1_212.csv。但是您的论文里有c4和c6，但代码里并没有使用c4和c6，是不是c1就足够来做异常检测了？然后是，c1文件夹里有c1_1_1到c1_1_315，还有一个c1_wear.csv，不太理解为什么c_1_212.csv代表异常数据。这个是怎么选取的？为什么没有使用这个磨损数据c1_wear.csv？还有您的这个代码可以应用于轴承故障诊断吗？就是比如使用凯斯西储大学数据集，是一维数据，而您的代码是三通道，我自己怎么权衡，从哪些方面入手更改代码？谢谢您。因为自己不太能入手。

**Comment by yanshen0210** [comment]
c1,c4和c6是三个刀具磨损量的数据集，任选择其一都能实现异常检测。
c1_wear.csv记录的是c1数据集中刀具的磨损量，单位为um。
为了便于代码的演示，随机选取一组异常数据c_1_212.csv，其对应的磨损量较大，故可代表为异常状态。
我没试过用其进行轴承的故障诊断，您可以尝试将损失函数换为交叉熵函数试试其效果。
若为单传感器数据，将网络的输入通道调整为1即可。

**Comment by zhulewen1998** [comment]
谢谢您的回复
